# Generated by Django 4.1.6 on 2023-02-10 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='عنوان')),
                ('filter_title', models.SlugField(max_length=45, verbose_name='عنوان فیلتر')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=35, verbose_name='مقدار')),
                ('filter_value', models.SlugField(max_length=45, verbose_name='مقدار فیلتر')),
                ('attribute', models.ForeignKey(blank=True, help_text='این مقدار متعلق به کدام ویژگی است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='product.attribute', verbose_name='ویژگی\u200c')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='عنوان')),
                ('url', models.SlugField(help_text='این فبلد بر روی سئو تاثیر گذار است، موارد مربوطه رعایت شود', max_length=130, unique=True, verbose_name='آدرس صفحه')),
                ('cover_img', models.ImageField(blank=True, help_text='این عکس به عنوان کاور محصول استفاده میشود', null=True, upload_to='categories/', verbose_name='تصویر کاور')),
                ('products_count', models.PositiveIntegerField(default=0, verbose_name='تعداد محصولات')),
                ('parent', models.ForeignKey(blank=True, help_text='والد دسته بندی را مشخص کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='به عنوان مثال قرمز', max_length=20, verbose_name='نام رنگ')),
                ('rgb', models.CharField(help_text='کد rgb رنگ مورد نظر', max_length=6, verbose_name='کد رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='عنوان')),
                ('brand', models.CharField(blank=True, help_text='این فیلد اختیاری است', max_length=130, null=True, verbose_name='برند')),
                ('url', models.SlugField(help_text='این فیلد بر روی سئو تاثیر گذار است، موارد مربوطه رعایت شود', max_length=300, unique=True, verbose_name='آدرس صفحه')),
                ('cover_img', models.ImageField(blank=True, help_text='این عکس به عنوان کاور محصول استفاده میشود', null=True, upload_to='products/covers/', verbose_name='تصویر کاور')),
                ('description', models.TextField(blank=True, help_text='معرفی و توضیحات را در این قسمت بنویسید', null=True, verbose_name='توضیحات')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین تغییر')),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='دسته بندی')),
                ('likes', models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='علاقه\u200cمندی\u200cها`')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(help_text='محصولاتی که این ویژگی را دارند درج کنید', on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.product', verbose_name='محصولات')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute', verbose_name='نام')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attributevalue', verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصولات',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty', models.CharField(blank=True, help_text='میتوانید این فیلد را خالی بگذارید', max_length=50, null=True, verbose_name='گارانتی')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت')),
                ('discount_percent', models.FloatField(blank=True, default=0, null=True, verbose_name='درصد تخفیف')),
                ('initial_balance', models.PositiveIntegerField(default=0, help_text='تعدادی که موجود دارید را وارد کنید، اگر تعداد بیشتری موجود شد مقدار این قسمت را افزایش دهید', verbose_name='موجودی اولیه انبار')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='تعداد فروخته شده')),
                ('special_offer', models.BooleanField(default=False, verbose_name='تخفیف ویژه')),
                ('attribute', models.ForeignKey(blank=True, help_text='ویژگی تاثیر گذار در قیمت را وارد کنید', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productattribute', verbose_name='ویژگی')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قیمت محصول',
                'verbose_name_plural': 'قیمت\u200cهای محصولات',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='این عکس به عنوان کاور محصول استفاده میشود', upload_to='products/', verbose_name='تصویر')),
                ('product', models.ForeignKey(help_text='محصولی که تصویر به آن تعلق دارد را انتخاب کنید', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(help_text='تعیین کنید فیلتر مربوط به کدام دسته بندی\u200cها است', related_name='attributes', to='product.category', verbose_name='دسته بندی\u200cها'),
        ),
    ]
