# Generated by Django 4.2.3 on 2023-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='initial_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی اولیه انبار'),
        ),
    ]
