# Generated by Django 3.2 on 2022-10-07 08:24

import apps.blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=apps.blog.models.image_directory, verbose_name='عکس اصلی')),
                ('title', models.CharField(max_length=185, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='آدرس صفحه')),
                ('content', tinymce.models.HTMLField(verbose_name='محتوا')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='پیش نمایش')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
    ]
