# Generated by Django 4.1.6 on 2023-02-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_created_at_post_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='main_image',
            new_name='cover_img',
        ),
    ]
