# Generated by Django 4.1.6 on 2023-02-10 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=48478514, max_length=8, unique=True, verbose_name='شماره سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='سفارش داده شده در تاریخ')),
                ('tracking_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='کد رهگیری پستی')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='نام گیرنده')),
                ('receiver_phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن گیرنده')),
                ('receiver_state', models.CharField(max_length=15, verbose_name='استان گیرنده')),
                ('receiver_city', models.CharField(max_length=15, verbose_name='شهر گیرنده')),
                ('receiver_address', models.CharField(max_length=650, verbose_name='آدرس گیرنده')),
                ('receiver_postal_code', models.CharField(max_length=18, verbose_name='کدپستی  گیرنده')),
                ('receiver_extra_data', models.CharField(blank=True, max_length=350, null=True, verbose_name='توضیحات اضافه')),
                ('post_price', models.IntegerField(blank=True, null=True, verbose_name='هزینه پست')),
                ('pay_method', models.CharField(blank=True, max_length=15, null=True, verbose_name='روش پرداخت')),
                ('pay_status', models.CharField(choices=[('N', 'در انتظار پرداخت'), ('Y', 'پرداخت شده')], default=('N', 'در انتظار پرداخت'), max_length=35, verbose_name='وضعیت پرداخت')),
                ('ordered_by', models.CharField(blank=True, max_length=10, null=True, verbose_name='سفارش توسط')),
                ('status', models.CharField(choices=[('در حال پردازش', 'در حال پردازش'), ('ارسال شده', 'ارسال شده'), ('تحویل مرسوله به مشتری', 'تحویل مرسوله به مشتری'), ('لغو شده', 'لغو شده'), ('مرجوع شده', 'مرجوع شده')], default='در حال پردازش', max_length=40, verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True, verbose_name='تعداد')),
                ('filled_price', models.CharField(blank=True, max_length=12, null=True, verbose_name='قیمت خریداری شده')),
                ('discount', models.CharField(blank=True, max_length=500, null=True, verbose_name='میزان تخفیف')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order', verbose_name='سفارش')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.price', verbose_name='قیمت')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول سفارش داده شده',
                'verbose_name_plural': 'محصولات سفارش داده شده',
            },
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_order_id', models.CharField(default=75348660, max_length=8, unique=True, verbose_name='شماره سفارش مرجوعی')),
                ('description', models.CharField(blank=True, max_length=555, null=True, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='order.order', verbose_name='سفارش')),
                ('products', models.ManyToManyField(related_name='returned_items', to='order.orderproduct', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سفارش مرجوعی',
                'verbose_name_plural': 'سفارشات مرجوعی',
            },
        ),
    ]
