# Generated by Django 4.1.6 on 2023-02-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=89141871, max_length=8, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_order_id',
            field=models.CharField(default=95257546, max_length=8, unique=True, verbose_name='شماره سفارش مرجوعی'),
        ),
    ]
