# Generated by Django 4.1.6 on 2023-07-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_ordered_by_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=17185710, max_length=8, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(blank=True, default='online', max_length=15, null=True, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_order_id',
            field=models.CharField(default=29295631, max_length=8, unique=True, verbose_name='شماره سفارش مرجوعی'),
        ),
    ]
