# Generated by Django 4.1.6 on 2023-07-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=45784903, max_length=8, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_order_id',
            field=models.CharField(default=51955131, max_length=8, unique=True, verbose_name='شماره سفارش مرجوعی'),
        ),
    ]
