# Generated by Django 4.2.3 on 2023-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=17504701, max_length=8, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='ساخته شده در'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_order_id',
            field=models.CharField(default=75580749, max_length=8, unique=True, verbose_name='شماره سفارش مرجوعی'),
        ),
    ]
