# Generated by Django 4.2.3 on 2023-08-04 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_order_id_alter_returnorder_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='ساخته شده در'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=62239140, max_length=8, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='created_at',
            field=models.DateTimeField(auto_created=True, verbose_name='ساخته شده در'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_order_id',
            field=models.CharField(default=23371861, max_length=8, unique=True, verbose_name='شماره سفارش مرجوعی'),
        ),
    ]
