# Generated by Django 4.2.3 on 2023-08-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_orderproduct_created_at_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_created=True, verbose_name='سفارش داده شده در تاریخ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=91721325, max_length=8, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_order_id',
            field=models.CharField(default=28857969, max_length=8, unique=True, verbose_name='شماره سفارش مرجوعی'),
        ),
    ]
