# Generated by Django 4.1.6 on 2023-02-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='files/', verbose_name='عکس اسلایدر')),
                ('title', models.CharField(max_length=130, verbose_name='عنوان')),
                ('message', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات')),
                ('button_action', models.CharField(blank=True, help_text='یا لینکمستقسم خارجی یا به صورت \u200c{% urls "Address" %}', max_length=300, null=True, verbose_name='لینک دکمه')),
            ],
        ),
    ]
