# Generated by Django 4.2.3 on 2023-07-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_slider_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='alt',
            new_name='title',
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='قعال'),
        ),
    ]
