# Generated by Django 4.2.3 on 2023-07-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_alt_brand_title_brand_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, help_text='برای سيوی بهتر این فیلد را پر کنید', max_length=20, null=True, verbose_name='عنوان'),
        ),
    ]
