# Generated by Django 3.2 on 2022-10-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='عنوان')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد تخفیف')),
                ('percent', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('apply_to', models.CharField(choices=[('all', 'همه'), ('products', 'دسته بندی خاص'), ('categories', 'محصولات خاص')], default='all', max_length=10, verbose_name='اعمال روی')),
                ('valid_from', models.DateTimeField(verbose_name='فعال از تاریخ')),
                ('valid_to', models.DateTimeField(verbose_name='فعال تا تاریخ')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('categories', models.ManyToManyField(related_name='coupons', to='product.Category', verbose_name='دسته بندی ها')),
                ('products', models.ManyToManyField(related_name='coupons', to='product.Product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'کوپن',
                'verbose_name_plural': 'کوپن ها',
            },
        ),
    ]
